### ISSUE TITLE
Problém s odpovědí serveru při dotaz na firemní údaje

### ISSUE THREAD

**Issue by MartinN3** [Foxentry/Javascript-API#2]
Nefunguje naseptavac fakturacni adresy od vikendu.

**Comment by tomasmrazko** [comment]
@MartinN3 
Môžem poprosiť o URL webu, na ktorom vám to nefunguje? (sem ako komentár alebo napíšte na info@foxentry.cz a pozrieme sa na to.

**Comment by MartinN3** [comment]
Zkoušel jsem to nyní a fungujeme.
